Ubuntu Container

diff --git a/cu124-megapak/Dockerfile b/cu124-megapak/Dockerfile
--- a/cu124-megapak/Dockerfile
+++ b/cu124-megapak/Dockerfile
@@ -2,47 +2,73 @@
 # Dockerfile that builds 'yanwk/comfyui-boot:cu124-megapak'
 # A big all-in-one package with many custom nodes.
 # Using CUDA 12.4, Python 3.12, GCC 13.
-# The container will be running in root (easy for rootless deploy).
 ################################################################################
 
-FROM docker.io/opensuse/tumbleweed:latest
-
-LABEL maintainer="YAN Wenkun <code@yanwk.fun>"
-
-RUN set -eu
+FROM nvidia/cuda:12.1.0-base-ubuntu22.04
 
 ################################################################################
-# NVIDIA CUDA devel
-# Ref: https://gitlab.com/nvidia/container-images/cuda/
+# Set environment variables to avoid interactive prompts
+################################################################################
 
-RUN --mount=type=cache,target=/var/cache/zypp \
-    printf "\
-[cuda-opensuse15-x86_64]\n\
-name=cuda-opensuse15-x86_64\n\
-baseurl=https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64\n\
-enabled=1\n\
-gpgcheck=1\n\
-gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64/D42D0685.pub\n" \
-        > /etc/zypp/repos.d/cuda-opensuse15.repo \
-    && zypper --gpg-auto-import-keys \
-        install --no-confirm --no-recommends --auto-agree-with-licenses \
-cuda-cccl-12-4 \
-cuda-command-line-tools-12-4 \
-cuda-compat-12-4 \
-cuda-cudart-12-4 \
-cuda-cudart-devel-12-4 \
-cuda-libraries-12-4 \
-cuda-libraries-devel-12-4 \
-cuda-minimal-build-12-4 \
-cuda-nvcc-12-4 \
-cuda-nvml-devel-12-4 \
-cuda-nvprof-12-4 \
-cuda-nvrtc-devel-12-4 \
-cuda-nvtx-12-4 \
-libcublas-12-4 \
-libcublas-devel-12-4 \
-libnpp-12-4 \
-libnpp-devel-12-4
+ENV DEBIAN_FRONTEND=noninteractive
+ENV TZ=Etc/UTC
+
+################################################################################
+# Install essential system tools, video libraries, OpenGL, and add Python 3.12
+################################################################################
+
+# Install dependencies for add-apt-repository
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    software-properties-common \
+    python3-apt \
+    curl \
+    ca-certificates
+
+# Add deadsnakes PPA for Python 3.12
+RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update
+
+# Install Python 3.12
+RUN apt-get install -y python3.12 python3.12-distutils
+
+# Set up Python alternatives
+RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
+    update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1
+
+
+
+# Install Python 3.12, GCC 13, and other system dependencies
+RUN apt update && apt install -y \
+    libglib2.0-0 \
+    make \
+    ninja-build \
+    git \
+    aria2 \
+    fish \
+    fd-find \
+    vim \
+    libopencv-dev \
+    ffmpeg \
+    libx264-dev \
+    libx265-dev \
+    fonts-noto-core \
+    fonts-noto-cjk \
+    fonts-noto-color-emoji \
+    && ln -sf /usr/bin/fdfind /usr/bin/fd \
+    && ln -sf /usr/bin/ninja-build /usr/bin/ninja \
+    && ln -sf /usr/lib/x86_64-linux-gnu/libx264.so /usr/lib/x264 \
+    && ln -sf /usr/lib/x86_64-linux-gnu/libx265.so /usr/lib/x265
+
+
+RUN which aria2c || echo "aria2c not found"
+
+
+# Install pip for Python 3.12
+RUN curl https://bootstrap.pypa.io/get-pip.py | python3.12
+
+################################################################################
+# Set environment variables for CUDA paths
+################################################################################
 
 ENV PATH="${PATH}:/usr/local/cuda-12.4/bin" \
     LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda-12.4/lib64" \
@@ -50,102 +76,102 @@ ENV PATH="${PATH}:/usr/local/cuda-12.4/bin" \
     CUDA_HOME="/usr/local/cuda-12.4"
 
 ################################################################################
-# Python and tools
-# Since this image is so big, we use openSUSE-verified PIP packages for compatibility.
+# Install Python packages using pip
+################################################################################
 
-RUN --mount=type=cache,target=/var/cache/zypp \
-    zypper addrepo --check --refresh --priority 90 \
-        'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/Essentials/' packman-essentials \
-    && zypper --gpg-auto-import-keys \
-        install --no-confirm --auto-agree-with-licenses \
-python312-devel \
-python312-pip \
-python312-wheel \
-python312-setuptools \
-python312-Cython \
-python312-py-build-cmake \
-python312-aiohttp \
-python312-dbm \
-python312-ffmpeg-python \
-python312-GitPython \
-python312-httpx \
-python312-joblib \
-python312-lark \
-python312-matplotlib \
-python312-mpmath \
-python312-numba-devel \
-python312-numpy \
-python312-onnx \
-python312-opencv \
-python312-pandas \
-python312-qrcode \
-python312-rich \
-python312-scikit-build \
-python312-scikit-build-core-pyproject \
-python312-scikit-image \
-python312-scikit-learn \
-python312-scipy \
-python312-svglib \
-python312-tqdm \
-Mesa-libGL1 \
-Mesa-libEGL-devel \
-libgthread-2_0-0 \
-make \
-ninja \
-git \
-aria2 \
-fish \
-fd \
-vim \
-opencv \
-opencv-devel \
-ffmpeg \
-x264 \
-x265 \
-google-noto-sans-fonts \
-google-noto-sans-cjk-fonts \
-google-noto-coloremoji-fonts \
-    && rm /usr/lib64/python3.12/EXTERNALLY-MANAGED \
-    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 100
+RUN pip install --no-cache-dir \
+    wheel \
+    setuptools \
+    cython \
+    aiohttp \
+    gitpython \
+    httpx \
+    joblib \
+    matplotlib \
+    numba \
+    numpy \
+    onnx \
+    opencv-python-headless \
+    pandas \
+    qrcode \
+    rich \
+    scikit-build \
+    scikit-learn \
+    scipy \
+    svglib \
+    tqdm \
+    ffmpeg-python \
+    lark-parser
 
 ################################################################################
-# GCC 13 
-# Required for compiling CUDA 12.4-related code.
-
-RUN --mount=type=cache,target=/var/cache/zypp \
-    zypper --gpg-auto-import-keys \
-        install --no-confirm --auto-agree-with-licenses \
-gcc13 \
-gcc13-c++ \
-cpp13 \
-    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-13 90 \
-    && update-alternatives --install /usr/bin/cc  cc  /usr/bin/gcc-13 90 \
-    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-13 90 \
-    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 90 \
-    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 90 \
-    && update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-13 90 \
-    && update-alternatives --install /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-13 90 \
-    && update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-13 90 \
-    && update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 90 \
-    && update-alternatives --install /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-13 90 \
-    && update-alternatives --install /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-13 90 
-
-################################################################################
-# Python Packages
-
 # PyTorch, xFormers
-RUN --mount=type=cache,target=/root/.cache/pip \
-    pip list \
-    && pip install \
-        --upgrade pip wheel setuptools \
-    && pip install \
-        xformers torchvision torchaudio \
-        --index-url https://download.pytorch.org/whl/cu124 \
-        --extra-index-url https://pypi.org/simple
+################################################################################
 
-# Bind libs (.so files)
-# Even we have CUDA installed by Zypper, we still need to install CUDA libs for Python in order to run PyTorch.
-# What's more, NVIDIA's openSUSE15 repo didn't provide CuDNN & NCCL, we have to use Python packages anyway.
+RUN --mount=type=cache,target=/root/.cache/pip \
+    pip list && \
+    pip install --upgrade pip wheel setuptools && \
+    pip install xformers torchvision torchaudio \
+    --index-url https://download.pytorch.org/whl/cu124 \
+    --extra-index-url https://pypi.org/simple
+
+################################################################################
+# Install additional fonts
+################################################################################
+
+#RUN apt-get update && apt-get install -y --no-install-recommends \
+#    fonts-noto \
+#    fonts-noto-cjk \
+#    fonts-noto-color-emoji \
+#    google-noto-sans-fonts \
+#    google-noto-sans-cjk-fonts \
+#    google-noto-coloremoji-fonts && \
+#    apt-get clean && \
+#    rm -rf /var/lib/apt/lists/*
+
+################################################################################
+# Additional Setup for CUDA libraries (optional, if needed)
+################################################################################
+
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    --allow-change-held-packages \
+    libcublas-12-4 \
+    libcublas-dev-12-4 \
+    libnpp-12-4 \
+    libnpp-dev-12-4 && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/*
+
+################################################################################
+# Copy builder scripts and install custom packages (ComfyUI & custom nodes)
+################################################################################
+
+COPY builder-scripts/.  /builder-scripts/
+
+# 1. Install dependencies for ComfyUI & custom nodes.
+# 2. Fix ONNX Runtime "missing CUDA provider" and add support for CUDA 12.
+# 3. Fix MediaPipe's broken dependency (protobuf<4).
+RUN --mount=type=cache,target=/root/.cache/pip \
+    pip install \
+        -r /builder-scripts/pak3.txt && \
+    pip install \
+        -r /builder-scripts/pak5.txt && \
+    pip install \
+        -r /builder-scripts/pak7.txt && \
+    pip uninstall --break-system-packages --yes \
+        onnxruntime-gpu && \
+    pip --no-cache-dir install --break-system-packages \
+        onnxruntime-gpu \
+        --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ \
+        --extra-index-url https://pypi.org/simple && \
+    pip install \
+        mediapipe && \
+    pip list
+
+################################################################################
+# Bind CUDA-related shared libraries for Python
+################################################################################
+
 ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}\
 :/usr/local/lib64/python3.12/site-packages/torch/lib\
 :/usr/local/lib/python3.12/site-packages/nvidia/cuda_cupti/lib\
@@ -161,32 +187,16 @@ ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}\
 :/usr/local/lib/python3.12/site-packages/nvidia/nvjitlink/lib\
 :/usr/local/lib/python3.12/site-packages/nvidia/nvtx/lib"
 
-COPY builder-scripts/.  /builder-scripts/
-
-# 1. Deps for ComfyUI & custom nodes
-# 2. Fix ONNX Runtime "missing CUDA provider". Also add support for CUDA 12. Ref: https://onnxruntime.ai/docs/install/
-# 3. Fix MediaPipe's broken dep (protobuf<4).
-RUN --mount=type=cache,target=/root/.cache/pip \
-    pip install \
-        -r /builder-scripts/pak3.txt \
-    && pip install \
-        -r /builder-scripts/pak5.txt \
-    && pip install \
-        -r /builder-scripts/pak7.txt \
-    && pip uninstall --break-system-packages --yes \
-        onnxruntime-gpu \
-    && pip --no-cache-dir install --break-system-packages \
-        onnxruntime-gpu \
-        --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ \
-        --extra-index-url https://pypi.org/simple \
-    && pip install \
-        mediapipe \
-    && pip list
-
+################################################################################
+# Cleanup files to minimize image size
 ################################################################################
 
-RUN du -ah /root \
-    && find /root/ -mindepth 1 -delete
+RUN du -ah /root && \
+    find /root/ -mindepth 1 -delete
+
+################################################################################
+# Copy runner scripts and set up final environment
+################################################################################
 
 COPY runner-scripts/.  /runner-scripts/
 
@@ -195,4 +205,9 @@ VOLUME /root
 WORKDIR /root
 EXPOSE 8188
 ENV CLI_ARGS=""
+
 CMD ["bash","/runner-scripts/entrypoint.sh"]
+
+################################################################################
+# End of Dockerfile
+################################################################################
